[package]
name = "oracle"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
simple_logger = "5.1.0"
tokio = {version = "1.48.0", features = ["full"]}
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"